[build]
command = "npm run build && env"

[context.deploy-preview]
command = "npm run build"

[context.main.environment]
ELDEN_ENV_01 = "Elden"
ELDEN_ENV_02 = "Williams"

[context.testing.environment]
ELDEN_ENV_03 = "Is the"
ELDEN_ENV_04 = "Greatest"

[[headers]]
    for = "/*"
    [headers.values]
    toml-header = "Header created using .toml file"

[[redirects]]
    from = "/api"
    to = "https://futuregerald-requestbin.herokuapp.com/w32z4kw3"
