[build]
[context.main]
command = "npm run build && env"

[context.deploy-previews]
command = "npm run build"

[[headers]]
    for = "/*"
    [headers.values]
    toml-header: Header created using .toml file